"""create users table

Revision ID: 21667d34885d
Revises: 504f7dfdc525
Create Date: 2025-05-11 03:37:28.070143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21667d34885d'
down_revision = '504f7dfdc525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
