"""create images table

Revision ID: 33cdf8a60e59
Revises: cf46447b386d
Create Date: 2025-05-11 00:28:12.939058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cdf8a60e59'
down_revision = 'cf46447b386d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
