"""create chapter  table

Revision ID: 7040e1efc9b4
Revises: 3901996413e2
Create Date: 2025-05-10 23:05:35.823166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7040e1efc9b4'
down_revision = '3901996413e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_name', sa.String(length=100), nullable=False),
    sa.Column('prologue', sa.Text(), nullable=True),
    sa.Column('epilogue', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_user_id'), 'chapter', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_user_id'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
