"""image table 수정


Revision ID: 905345ae99d3
Revises: 21667d34885d
Create Date: 2025-05-11 06:02:34.334997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905345ae99d3'
down_revision = '21667d34885d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('main_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'main_image_url')
    # ### end Alembic commands ###
