"""modify image  table

Revision ID: c2356e0dcec5
Revises: 905345ae99d3
Create Date: 2025-05-11 07:48:21.164797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2356e0dcec5'
down_revision = '905345ae99d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'file_url',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'file_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
