"""create images table

Revision ID: cf46447b386d
Revises: 0d0e254d14ff
Create Date: 2025-05-10 23:57:16.034829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf46447b386d'
down_revision = '0d0e254d14ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
