"""create image  table

Revision ID: d29db7d57aac
Revises: 33cdf8a60e59
Create Date: 2025-05-11 00:56:54.589905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29db7d57aac'
down_revision = '33cdf8a60e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
